### ISSUE TITLE
torch.nn.modules.module.ModuleAttributeError: 'DistributedDataParallel' object has no attribute 'module_list'

### ISSUE THREAD

**Issue by Bingcor** [zbyuan/pruning_yolov3#2]
我在执行正常训练的指令的时候（没有剪枝），报下面这个错误，请问您知道是什么原因吗？
 plt.subplot(ns, ns, i + 1).imshow(imgs[i].transpose(1, 2, 0))
  0%|                                                                                                                                               | 0/297 [00:07<?, ?it/s]
Traceback (most recent call last):
  File "train_pru.py", line 457, in <module>
    train()  # train normally
  File "train_pru.py", line 306, in train
    BNOptimizer.updateBN(sr_flag, model.module_list, opt.s, prune_idx)
  File "/home/share/lib/python3.7/site-packages/torch/nn/modules/module.py", line 772, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'DistributedDataParallel' object has no attribute 'module_list'

**Comment by zbyuan** [comment]
你用这个吧  https://github.com/tanluren/yolov3-channel-and-layer-pruning这个跟新了好多   配置好数据pytorch的版本>=1.1 不知最新的版本支持吗
